nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.144.232
    path: /volume1/kubernetes-nosquash/prod
  storageClass:
    name: nfs-nosquash
    defaultClass: false
    provisionerName: k8s-sigs.io/prod-nosquash
    pathPattern: ${.PVC.namespace}-${.PVC.name}
