nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.144.232
    path: /volume1/kubernetes-nosquash/tools
  storageClass:
    name: nfs-nosquash
    defaultClass: false
    pathPattern: ${.PVC.namespace}-${.PVC.name}
